apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  namespace: "notejam"
  name: "notejam-incoming"
spec:
  tls:
  - secretName: ingress-crt-key
  backend:
    serviceName: "notejam"
    servicePort: 80
